### ISSUE TITLE
[依頼]　フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Ras1128** [Ras1128/furima-32544#11]
自身のフリマアプリのURL 

自身のフリマアプリのURL | 本番環境(Heroku)のURL
https://furima-32544.herokuapp.com/
Basic認証のIDとパスワード 
admin
2222
出品者用のメールアドレスとパスワード
ry0w.cimba@gmail.com
cimba2106
購入者用のメールアドレスとパスワード | 上記とは異なる、本番環境で使用可能なユーザーの情報ryo@cimba
cimba2106

購入用カードの番号・期限・セキュリティコード | PAY.JPのテストカード情報
番号　4242424242424242
CVC　123
期限　3/23

**Comment by mutorisa** [comment]
@Ras1128 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

**[修正依頼箇所]**

- [x] 商品詳細ページの「商品説明欄」にデフォルトの文字が表示されており、商品出品時に登録した「商品説明」が表示されていない状態です。正しい情報が表示されるよう修正しましょう。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by mutorisa** [comment]
再度ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/65144927/104877965-5888d780-599e-11eb-9bdb-2a996216b8c5.png)


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
